# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: bitnami/postgresql:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    networks:
      - pgnetwork
    volumes:
      - "./data:/bitnami/postgresql"
    ports:
      - 5432:5432

  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: email@provider.com
      PGADMIN_DEFAULT_PASSWORD: mypassword
    ports:
      - 27018:80
    networks:
      - pgnetwork

networks:
  pgnetwork:
    driver: bridge
